name: Hindi Dubber

on:
  workflow_dispatch:
    inputs:
      INPUT_VIDEO_PATH:
        description: 'Path to the input video file'
        required: true
        default: 'input/input_video.mp4'
      OUTPUT_VIDEO_PATH:
        description: 'Path to the output video file'
        required: true
        default: 'output/output_hindi_dubbed_video.mp4'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Update to the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Create temp and output directories
        run: |
          mkdir -p temp
          mkdir -p output

      - name: Run Hindi Dubber
        env:
          INPUT_VIDEO_PATH: ${{ github.event.inputs.INPUT_VIDEO_PATH }}
          OUTPUT_VIDEO_PATH: ${{ github.event.inputs.OUTPUT_VIDEO_PATH }}
        run: |
          python main.py
          
